# Generated by Django 5.0.7 on 2024-08-10 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='cgpa',
            field=models.FloatField(default=7.1),
            preserve_default=False,
        ),
    ]
