# Generated by Django 5.0.7 on 2024-08-11 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_education_cgpa'),
    ]

    operations = [
        migrations.AddField(
            model_name='certification',
            name='certiimage',
            field=models.ImageField(default=1, upload_to='certification/'),
            preserve_default=False,
        ),
    ]
