# Generated by Django 5.0.7 on 2024-08-15 04:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_skill_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='skill',
            old_name='image',
            new_name='skillimage',
        ),
    ]
