# Generated by Django 5.0.7 on 2024-08-18 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_rename_image_skill_skillimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='award',
            name='awardimage',
            field=models.ImageField(default=1, upload_to='certification/'),
            preserve_default=False,
        ),
    ]
